add_test( [==[Set/Get options]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Set/Get options]==]  )
set_tests_properties( [==[Set/Get options]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive single buffer]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive single buffer]==]  )
set_tests_properties( [==[Send/Receive single buffer]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive single message]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive single message]==]  )
set_tests_properties( [==[Send/Receive single message]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive synchronous]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive synchronous]==]  )
set_tests_properties( [==[Send/Receive synchronous]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive async]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive async]==]  )
set_tests_properties( [==[Send/Receive async]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Async send/receive copies buffer refs]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Async send/receive copies buffer refs]==]  )
set_tests_properties( [==[Async send/receive copies buffer refs]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive async is_speculative]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive async is_speculative]==]  )
set_tests_properties( [==[Send/Receive async is_speculative]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive async threads]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive async threads]==]  )
set_tests_properties( [==[Send/Receive async threads]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive message async]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive message async]==]  )
set_tests_properties( [==[Send/Receive message async]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Send/Receive message more async]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Send/Receive message more async]==]  )
set_tests_properties( [==[Send/Receive message more async]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Socket Monitor]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Socket Monitor]==]  )
set_tests_properties( [==[Socket Monitor]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Attach Method]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Attach Method]==]  )
set_tests_properties( [==[Attach Method]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( Pub/Sub /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket Pub/Sub  )
set_tests_properties( Pub/Sub PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( Loopback /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket Loopback  )
set_tests_properties( Loopback PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[socket_service does not call pending completion handlers when destroyed]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[socket_service does not call pending completion handlers when destroyed]==]  )
set_tests_properties( [==[socket_service does not call pending completion handlers when destroyed]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Async Operation Send/Receive with callback]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Async Operation Send/Receive with callback]==]  )
set_tests_properties( [==[Async Operation Send/Receive with callback]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Async Operation Send/Receive with future ]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Async Operation Send/Receive with future ]==]  )
set_tests_properties( [==[Async Operation Send/Receive with future ]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Async Operation Send/Receive with stackful coroutine]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Async Operation Send/Receive with stackful coroutine]==]  )
set_tests_properties( [==[Async Operation Send/Receive with stackful coroutine]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
add_test( [==[Async Operation Send/Receive single message, stackful coroutine, one message at a time]==] /workspaces/blunux-repos/azmq/build___unspec__/test/socket/test_socket [==[Async Operation Send/Receive single message\, stackful coroutine\, one message at a time]==]  )
set_tests_properties( [==[Async Operation Send/Receive single message, stackful coroutine, one message at a time]==] PROPERTIES WORKING_DIRECTORY /workspaces/blunux-repos/azmq/build___unspec__/test/socket)
set( test_socket_TESTS [==[Set/Get options]==] [==[Send/Receive single buffer]==] [==[Send/Receive single message]==] [==[Send/Receive synchronous]==] [==[Send/Receive async]==] [==[Async send/receive copies buffer refs]==] [==[Send/Receive async is_speculative]==] [==[Send/Receive async threads]==] [==[Send/Receive message async]==] [==[Send/Receive message more async]==] [==[Socket Monitor]==] [==[Attach Method]==] Pub/Sub Loopback [==[socket_service does not call pending completion handlers when destroyed]==] [==[Async Operation Send/Receive with callback]==] [==[Async Operation Send/Receive with future ]==] [==[Async Operation Send/Receive with stackful coroutine]==] [==[Async Operation Send/Receive single message, stackful coroutine, one message at a time]==])
