name: CMake

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config: 
          - os: ubuntu-24.04
            cc: gcc
            cxx: g++
          - os: ubuntu-22.04
            cc: gcc
            cxx: g++
          - os: ubuntu-20.04
            cc: gcc
            cxx: g++
          - os: macos-15
            cc: clang
            cxx: clang++
          - os: macos-14
            cc: clang
            cxx: clang++
          - os: macos-13
            cc: clang
            cxx: clang++
        boost:
          - url: system
            system_packages_ubuntu: libboost-all-dev
            system_packages_macos: boost
          - url: BOOST_187
            system_packages_ubuntu: 
            system_packages_macos: 
          - url: BOOST_184
            system_packages_ubuntu: 
            system_packages_macos:
          - url: BOOST_174
            system_packages_ubuntu: 
            system_packages_macos:
          - url: BOOST_170
            system_packages_ubuntu: 
            system_packages_macos:
        zmq: 
          - tag: system
            system_packages_ubuntu: libzmq3-dev
            system_packages_macos: zmq

    runs-on: ${{ matrix.config.os }}

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      CTEST_OUTPUT_ON_FAILURE: 1
      PACKAGES_UBUNTU: ${{ matrix.boost.system_packages_ubuntu }} ${{ matrix.zmq.system_packages_ubuntu }}
      PACKAGES_MACOS: ${{ matrix.boost.system_packages_macos }} ${{ matrix.zmq.system_packages_macos }}
      CONFIG_OS: ${{ matrix.config.os }}
      MATRIX: ${{ toJson(matrix) }}
      skip: false

    steps:
      - name: Exclude invalid configs
        run: |
          if [[ 
            (${{matrix.config.os}} == "ubuntu-22.04" && ${{matrix.boost.url}} == "BOOST_170") 
            || (${{matrix.config.os}} == "ubuntu-24.04" && ${{matrix.boost.url}} == "BOOST_170") 
            || (${{matrix.config.os}} == "macos-15" && ${{matrix.boost.url}} == "BOOST_170")
          ]]; then
            echo "### Skipping invalid config :no_entry_sign:" >> $GITHUB_STEP_SUMMARY
            echo "The OS/Boost combination might not be compatible" >> $GITHUB_STEP_SUMMARY
            echo "skip=true" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
      - name: buildtools on ubuntu
        if: startsWith(matrix.config.os, 'ubuntu') && ${{ !env.skip }}
        shell: bash
        run: |
          PACKAGES_UBUNTU=$(echo $PACKAGES_UBUNTU | sed 's/^[   ]*//;s/[    ]*$//')
          if [ -n "$PACKAGES_UBUNTU" ]; then
            sudo apt-get update && sudo apt-get install -y $PACKAGES_UBUNTU
          fi
      - name: buildtools on macos
        if: startsWith(matrix.config.os, 'macos') && ${{ !env.skip }}
        shell: bash
        run: |
          PACKAGES_MACOS=$(echo $PACKAGES_MACOS | sed 's/^[   ]*//;s/[    ]*$//')
          if [ -n "$PACKAGES_MACOS" ]; then
            brew install $PACKAGES_MACOS
          fi
      - name: build
        if: ${{ !env.skip }}
        shell: bash
        run: |
          cmake  -DBOOST_URL=${{matrix.boost.url}} -DZMQ_TAG=${{matrix.zmq.tag}} -S .github/workflows/cmake-superbuild  -B build
          cmake --build build
